"""
SOMA: Self-Organizing Memory Agent
==================================

Description:
------------
This module provides the core state management primitives for the SOMA Agent's 
execution logic. It defines state trackers that handle anomaly recovery, temporal 
bounds for critical steps, and sequential task progression. 

Key Components:
- RollbackState: Orchestrates dynamic reverse trajectories when the agent encounters 
  anomalies or gets stuck. It calculates reverse vectors and includes a stabilization 
  (buffer) phase before yielding control back to the primary policy.
- KeyStepRetryState: Monitors execution time against expected temporal boundaries 
  for critical sub-tasks, automatically triggering retries if the agent exceeds 
  the defined timeout thresholds.
- TaskDecomposeState: Manages the progression of subtasks generated by the high-level 
  reasoning module. It implements temporal smoothing (hold counters) to prevent 
  premature task advancement caused by transient sensor noise.
"""

import logging
from dataclasses import dataclass, field
from typing import Any, List

import numpy as np


@dataclass
class RollbackState:
    """
    Manages the logic and state for executing a robotic rollback (reverse trajectory).
    This allows the agent to safely back away from failed or stuck configurations.
    """
    active: bool = False
    phase: str = ""  # "reverse" | "buffer" | "done"
    reverse_steps_total: int = 100
    buffer_steps_total: int = 25
    reverse_step_idx: int = 0
    buffer_step_idx: int = 0
    reverse_action: np.ndarray | None = None  # Expected shape: (B, D)
    reason: str = ""
    need_hard_reset: bool = False
    
    # Dimensionality of the action space, dynamically inferred to prevent hardcoding
    action_dim: int = 7 

    def start_from_accumulated(self, accumulated_actions: np.ndarray, *, reverse_steps: int = 100, buffer_steps: int = 25, reason: str = ""):
        """
        Initializes the rollback sequence using the accumulated actions to determine the reverse vector.
        
        Args:
            accumulated_actions: Array of shape (B, D) representing the accumulated forward actions.
            reverse_steps: Duration of the reverse phase.
            buffer_steps: Duration of the stabilization phase post-reversal.
            reason: Logging string detailing why the rollback was triggered.
        """
        self.active = True
        self.phase = "reverse"
        self.reverse_steps_total = int(reverse_steps)
        self.buffer_steps_total = int(buffer_steps)
        self.reverse_step_idx = 0
        self.buffer_step_idx = 0
        
        # Dynamically infer the action dimensionality
        if accumulated_actions.ndim > 1:
            self.action_dim = accumulated_actions.shape[-1]
        
        # Calculate the reverse step vector. 
        # The denominator is clamped to 1 to prevent division by zero.
        self.reverse_action = -accumulated_actions / max(1, self.reverse_steps_total)
        self.reason = reason
        
        logging.warning(
            f"[CTRL] Rollback Initiated | Reason: {reason} | Total Steps: {self.reverse_steps_total} | Action Dim: {self.action_dim}"
        )

    def step_action(self, num_envs: int) -> np.ndarray:
        """
        Advances the rollback state machine by one step and returns the appropriate action.
        """
        if not self.active or self.reverse_action is None:
            raise RuntimeError("RollbackState.step_action was called, but the rollback state is not active.")

        # === Phase 1: Reverse Trajectory Execution ===
        if self.phase == "reverse":
            self.reverse_step_idx += 1
            if self.reverse_step_idx >= self.reverse_steps_total:
                # Transition to the stabilization buffer or complete the rollback
                self.phase = "buffer" if self.buffer_steps_total > 0 else "done"
            
            return self.reverse_action.astype(np.float32)

        # === Phase 2: Stabilization Buffer ===
        if self.phase == "buffer":
            self.buffer_step_idx += 1
            
            # Dynamically generate zero-action arrays based on the inferred dimension.
            # By default, the gripper action (last dimension) is set to -1.0 (open) during stabilization.
            dummy_action = np.zeros(self.action_dim, dtype=np.float32)
            if self.action_dim >= 1:
                dummy_action[-1] = -1.0 
            
            if self.buffer_step_idx >= self.buffer_steps_total:
                self.phase = "done"
            
            return np.array([dummy_action] * num_envs, dtype=np.float32)

        # === Phase 3: Completion ===
        self.need_hard_reset = True 
        self.reset() 
        
        # Return zeroed actions, yielding control back to the primary policy
        return np.zeros((num_envs, self.action_dim), dtype=np.float32)

    def reset(self):
        """Forces a hard reset of the internal logic state."""
        self.active = False
        self.phase = "done"
        self.reverse_action = None
        self.reason = ""


@dataclass
class KeyStepRetryState:
    """
    Monitors execution boundaries for critical tasks to trigger automatic retries 
    if the agent exceeds defined temporal limits.
    """
    key_steps: dict[str, int] = field(default_factory=lambda: {"start": 0, "end": 0, "timeout_grace": 0})
    armed: bool = False
    triggered: bool = False

    def update_from_control_flags(self, control_flags: dict[str, Any]):
        """Updates internal thresholds based on external control signals."""
        ks = control_flags.get("key_steps")
        if isinstance(ks, dict) and "start" in ks and "end" in ks:
            self.key_steps = {
                "start": int(ks.get("start", 0)),
                "end": int(ks.get("end", 0)),
                "timeout_grace": int(ks.get("timeout_grace", 0)),
            }
            self.armed = True
            self.triggered = False  # Reset the trigger flag upon updating configurations

        # Support forced retry overrides from control flags
        if control_flags.get("key_step_retry") is True:
            self.armed = True
            # Note: Do not immediately trigger; wait for the next evaluation step

    def should_trigger(self, *, step: int, success_any: bool) -> bool:
        """Evaluates whether a retry should be triggered based on current progress and time."""
        if not self.armed or self.triggered:
            return False
        
        # Disarm if the step succeeds to prevent false positive triggers
        if success_any:
            self.armed = False 
            return False
            
        end = self.key_steps.get("end", 0)
        grace = self.key_steps.get("timeout_grace", 0)
        
        # Trigger only when a valid boundary is defined and execution exceeds the timeout grace period
        return step >= (end + grace) and end > 0

    def mark_triggered(self):
        """Flags the state as triggered to prevent redundant retry signals."""
        self.triggered = True
        logging.warning(f"[CTRL] KeyStepRetry Triggered | Configuration: {self.key_steps}")
    
    def reset(self):
        """Resets the state to its default unarmed configuration."""
        self.armed = False
        self.triggered = False
        self.key_steps = {"start": 0, "end": 0, "timeout_grace": 0}


@dataclass
class TaskDecomposeState:
    """
    Manages the sequential progression of decomposed subtasks. Includes temporal 
    smoothing to prevent premature advancement caused by transient success signals.
    """
    subtasks: List[str] = field(default_factory=list)
    subtask_idx: int = 0
    
    # Success counter to prevent task jitter from sensor noise
    success_hold_steps: int = 0 

    def update_from_control_flags(self, control_flags: dict[str, Any]):
        """Updates the subtask sequence if a new sequence is provided."""
        sts = control_flags.get("subtasks")
        if isinstance(sts, list) and all(isinstance(x, str) for x in sts) and len(sts) > 0:
            # Update internal state only if the newly provided task sequence differs
            if sts != self.subtasks:
                self.subtasks = sts
                self.subtask_idx = 0
                self.success_hold_steps = 0
                logging.info(f"[CTRL] TaskDecompose Sequence Updated | Steps: {len(sts)} | Initial: {sts[0]}")

    def current_task(self, default_task: str) -> str:
        """Returns the active subtask or falls back to the default task."""
        if self.subtasks and 0 <= self.subtask_idx < len(self.subtasks):
            return self.subtasks[self.subtask_idx]
        return default_task

    def maybe_advance(self, *, success_any: bool):
        """
        Advances the task index upon successful execution.
        
        Note: In vectorized environments, `success_any=True` advances the sequence if 
        at least one environment succeeds. This is standard for evaluation but requires 
        caution if utilized during parallel training.
        """
        if not self.subtasks:
            return

        if success_any:
            # Implement a hold counter to filter out transient false-positive success signals
            self.success_hold_steps += 1
            if self.success_hold_steps >= 2:  # Require consistent success over 2 consecutive frames
                if self.subtask_idx < len(self.subtasks) - 1:
                    self.subtask_idx += 1
                    self.success_hold_steps = 0  # Reset the hold counter upon advancing
                    logging.info(f"[CTRL] Task Advanced >>> Step {self.subtask_idx}: {self.subtasks[self.subtask_idx]}")
                else:
                    # Terminal subtask reached; no further advancement
                    pass
        else:
            self.success_hold_steps = 0
            
    def reset(self):
        """Clears the task sequence and resets tracking metrics."""
        self.subtasks = []
        self.subtask_idx = 0
        self.success_hold_steps = 0